env:
  global:
    - NDK_VERSION=r10e
sudo: false
language: 
    - android
jdk:
  - oraclejdk8
android:
  components:
    # Uncomment the lines below if you want to
    # use the latest revision of Android SDK Tools
    # - tools
    # - platform-tools

    # The BuildTools version used by your project
    - build-tools-26.0.2

    # The SDK version used to compile your project
    - android-26

    # Additional components
    - extra-google-google_play_services
    - extra-google-m2repository
    - extra-android-m2repository
    - addon-google_apis-google-26

    # Specify at least one system image,
    # if you need to run emulator(s) during your tests
    #- sys-img-armeabi-v7a-android-26
    #- sys-img-armeabi-v7a-android-17

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq ant 
  - wget http://dl.google.com/android/ndk/android-ndk-$NDK_VERSION-linux-x86_64.bin
  - chmod +x android-ndk-$NDK_VERSION-linux-x86_64.bin
  - ./android-ndk-$NDK_VERSION-linux-x86_64.bin | egrep -v ^Extracting
  - export ANDROID_NDK_HOME=`pwd`/android-ndk-$NDK_VERSION
  - export PATH=${PATH}:${ANDROID_NDK_HOME}

script:
  -  ndk-build